import { useState } from "react";
import { Link } from "react-router-dom";
import QRCode from "qrcode";
import SEO from "../components/SEO";

function QRCodeGenerator() {
  const [text, setText] = useState("");
  const [qrCode, setQrCode] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);

  const generateQRCode = async () => {
    if (!text.trim()) {
      alert("Please enter text or a URL.");
      return;
    }

    try {
      setIsGenerating(true);

      const url = await QRCode.toDataURL(text.trim(), {
        width: 400,
        margin: 2,
        errorCorrectionLevel: "H",
      });

      setQrCode(url);
      setIsGenerating(false);
    } catch (error) {
      console.error(error);

      alert("Unable to generate QR code.");

      setIsGenerating(false);
    }
  };

  const downloadQRCode = () => {
    if (!qrCode) {
      return;
    }

    const link = document.createElement("a");

    link.href = qrCode;
    link.download = "toolora-qr-code.png";

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const clearQRCode = () => {
    setText("");
    setQrCode("");
  };

  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: [
      {
        "@type": "Question",
        name: "What is a QR code?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "A QR code is a two-dimensional barcode that can store information such as URLs, text and other data. Smartphones can scan the code to access that information.",
        },
      },
      {
        "@type": "Question",
        name: "Is Toolora's QR Code Generator free?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Yes. Toolora's QR Code Generator is free to use online.",
        },
      },
      {
        "@type": "Question",
        name: "Can I create a QR code for a website?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Yes. Enter the complete website URL into the QR Code Generator and create a QR code that contains the URL.",
        },
      },
      {
        "@type": "Question",
        name: "Can I download the generated QR code?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Yes. After generating a QR code, you can download it as a PNG image.",
        },
      },
      {
        "@type": "Question",
        name: "Does a QR code generated by Toolora expire?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "The QR code generated by Toolora contains the information you enter directly. The generated code itself does not depend on a Toolora account or subscription.",
        },
      },
    ],
  };

  return (
    <div className="compressor-page">

      <SEO
        title="QR Code Generator Online - Create QR Codes Free"
        description="Create QR codes online for free with Toolora. Generate a QR code for text, links and other information and download it easily."
        keywords="QR code generator, create QR code, QR code maker, generate QR code online, free QR code generator, QR code creator"
        canonical="/qr-code-generator"
      />

      <script type="application/ld+json">
        {JSON.stringify(faqSchema)}
      </script>

      <div className="container py-5">

        <header className="text-center mb-5">

          <div className="hero-badge mb-3">
            🔗 Free QR Tool
          </div>

          <h1 className="fw-bold">
            QR Code Generator Online
          </h1>

          <p
            className="text-muted mx-auto"
            style={{ maxWidth: "700px" }}
          >
            Create free QR codes for URLs, text and other
            information online. Generate and download your
            QR code as a PNG image.
          </p>

        </header>

        <main>

          <section
            className="compressor-box mx-auto"
            aria-label="QR code generator tool"
          >

            <div className="mb-4">

              <label
                htmlFor="qrCodeInput"
                className="form-label fw-semibold"
              >
                Enter Text or URL
              </label>

              <textarea
                id="qrCodeInput"
                className="form-control qr-input"
                rows="4"
                placeholder="https://example.com"
                value={text}
                onChange={(event) => {
                  setText(event.target.value);

                  if (qrCode) {
                    setQrCode("");
                  }
                }}
                aria-describedby="qrCharacterCount"
              />

              <div
                id="qrCharacterCount"
                className="text-end mt-2"
              >
                <small className="text-muted">
                  {text.length} characters
                </small>
              </div>

            </div>

            <div className="d-flex gap-3 justify-content-center flex-wrap">

              <button
                type="button"
                className="btn btn-primary px-4"
                onClick={generateQRCode}
                disabled={isGenerating}
              >
                {isGenerating
                  ? "Generating..."
                  : "Generate QR Code"}
              </button>

              {qrCode && (
                <button
                  type="button"
                  className="btn btn-success px-4"
                  onClick={downloadQRCode}
                >
                  Download PNG
                </button>
              )}

              {qrCode && (
                <button
                  type="button"
                  className="btn btn-outline-danger px-4"
                  onClick={clearQRCode}
                >
                  Clear
                </button>
              )}

            </div>

            {qrCode && (
              <div
                className="qr-preview mt-5 text-center"
                aria-live="polite"
              >

                <h2 className="h5 fw-bold mb-3">
                  Your Generated QR Code
                </h2>

                <div className="mb-3">

                  <img
                    src={qrCode}
                    alt="Generated QR code"
                    className="qr-image"
                  />

                </div>

                <p className="text-muted mb-0">
                  Scan this QR code with your phone camera.
                </p>

              </div>
            )}

          </section>

          <article className="tool-information mx-auto mt-5">

            <section>

              <h2>
                Free QR Code Generator Online
              </h2>

              <p>
                Toolora's free QR Code Generator lets you create
                QR codes for websites, URLs, text and other
                information. Enter your content, generate the
                QR code and download it as a PNG image.
              </p>

              <p>
                QR codes provide a convenient way to connect
                printed materials with digital information.
                They can be used for websites, menus, contact
                information, forms, events, business details
                and many other purposes.
              </p>

            </section>

            <section className="mt-4">

              <h2>
                How to Create a QR Code Online
              </h2>

              <p>
                Creating a QR code with Toolora only takes a
                few simple steps:
              </p>

              <ol>

                <li>
                  Enter your website URL, text or other
                  information.
                </li>

                <li>
                  Click <strong>Generate QR Code</strong>.
                </li>

                <li>
                  Preview the generated QR code.
                </li>

                <li>
                  Click <strong>Download PNG</strong> to
                  save the QR code as an image.
                </li>

              </ol>

            </section>

            <section className="mt-4">

              <h2>
                What Can You Put in a QR Code?
              </h2>

              <p>
                A QR code can be used to provide quick access
                to different types of digital information.
                With Toolora, you can generate a QR code from
                text or a URL.
              </p>

              <ul>

                <li>
                  Website URLs
                </li>

                <li>
                  Landing page links
                </li>

                <li>
                  Restaurant menus
                </li>

                <li>
                  Contact information
                </li>

                <li>
                  Social media profile links
                </li>

                <li>
                  Online forms
                </li>

                <li>
                  Event information
                </li>

                <li>
                  Business information
                </li>

                <li>
                  Plain text and messages
                </li>

              </ul>

            </section>

            <section className="mt-4">

              <h2>
                QR Codes for Websites and URLs
              </h2>

              <p>
                One of the most common uses of QR codes is
                sharing a website or webpage. Instead of
                manually typing a long web address, users can
                scan the QR code with a compatible smartphone
                camera.
              </p>

              <p>
                To create one, enter the complete URL, such as
                <strong> https://example.com</strong>, and
                generate your QR code.
              </p>

            </section>

            <section className="mt-4">

              <h2>
                QR Codes for Business and Marketing
              </h2>

              <p>
                Businesses can use QR codes on printed
                materials to make digital information easier
                to access. A QR code can be placed on menus,
                posters, flyers, packaging, business cards
                and promotional materials.
              </p>

              <p>
                The QR code can direct users to a website,
                menu, contact page, online form or other
                digital content.
              </p>

            </section>

            <section className="mt-4">

              <h2>
                Benefits of Using QR Codes
              </h2>

              <ul>

                <li>
                  Quick access to digital information.
                </li>

                <li>
                  Easy to scan with compatible smartphones.
                </li>

                <li>
                  Useful for personal and business purposes.
                </li>

                <li>
                  Connect printed materials with online content.
                </li>

                <li>
                  Avoid manually typing long URLs.
                </li>

                <li>
                  Easy to download and share as a PNG image.
                </li>

              </ul>

            </section>

            <section className="mt-4">

              <h2>
                Static QR Codes vs Dynamic QR Codes
              </h2>

              <p>
                A static QR code contains the information
                directly in the code. If the encoded information
                changes, a new QR code generally needs to be
                created.
              </p>

              <p>
                Dynamic QR code services typically use a
                redirect or management system that can allow
                the destination to be changed later. Toolora's
                generator creates QR codes containing the
                information you enter directly.
              </p>

            </section>

            <section className="mt-4">

              <h2>
                Download Your QR Code as a PNG
              </h2>

              <p>
                After generating your QR code, Toolora lets you
                download it as a PNG image. You can then use
                the downloaded image in digital documents,
                websites, presentations or printed materials.
              </p>

            </section>

            <section className="mt-4">

              <h2>
                Is Toolora QR Code Generator Free?
              </h2>

              <p>
                Yes. Toolora's QR Code Generator is free to
                use online. You can enter text or a URL,
                generate your QR code and download it as a
                PNG image.
              </p>

            </section>

            <section className="mt-5">

              <h2>
                Frequently Asked Questions
              </h2>

              <h3 className="mt-4">
                What is a QR code?
              </h3>

              <p>
                A QR code is a two-dimensional barcode that
                can store information such as URLs, text and
                other data. Compatible smartphones can scan
                the code to access that information.
              </p>

              <h3 className="mt-4">
                Is Toolora's QR Code Generator free?
              </h3>

              <p>
                Yes. Toolora's QR Code Generator is free to
                use online.
              </p>

              <h3 className="mt-4">
                Can I create a QR code for a website?
              </h3>

              <p>
                Yes. Enter the complete website URL, such as
                https://example.com, and generate your QR code.
              </p>

              <h3 className="mt-4">
                Can I download the generated QR code?
              </h3>

              <p>
                Yes. After generating the QR code, click the
                <strong> Download PNG</strong> button to save
                it as an image.
              </p>

              <h3 className="mt-4">
                Does a QR code generated by Toolora expire?
              </h3>

              <p>
                The QR code generated by Toolora contains the
                information you enter directly. The generated
                code does not depend on a Toolora account or
                subscription.
              </p>

            </section>

            <section className="mt-5">

              <h2>
                Try Our Other Free Tools
              </h2>

              <p>
                Explore more free online tools from Toolora:
              </p>

              <div className="d-flex flex-wrap gap-3 mt-3">

                <Link
                  to="/image-compressor"
                  className="btn btn-outline-primary"
                >
                  Image Compressor →
                </Link>

                <Link
                  to="/image-resizer"
                  className="btn btn-outline-primary"
                >
                  Image Resizer →
                </Link>

                <Link
                  to="/word-counter"
                  className="btn btn-outline-primary"
                >
                  Word Counter →
                </Link>

                <Link
                  to="/percentage-calculator"
                  className="btn btn-outline-primary"
                >
                  Percentage Calculator →
                </Link>

              </div>

            </section>

          </article>

        </main>

      </div>

    </div>
  );
}

export default QRCodeGenerator;

